### ISSUE TITLE
Methods API naming change

### ISSUE THREAD

**Issue by Sija** [anykeyh/await_async#2]
Firstly I'd like to say I really dig your shard m8, it's a neat piece of work 👍

One thing that looked odd (from a pedantic PoV, sic!) was method naming, so I thought you might be open for a change to sth more Crystal/Ruby-ish, like using `!` to denote a variant. My suggestion is renaming `async` to `async!` and `async_lp` to `async` - in this case `!` would stand for future started _now_, in contrast to non-`!` variant which gets computed eagerly.

Just my 2c, thanks for listening :)

**Comment by anykeyh** [comment]
Actually it's an interesting idea. It's definitely more beautiful !

I'll keep this issue open. Let's see what final users think about it, since it's a breaking change.

**Comment by iambudi** [comment]
Agree to change soon for better readability. async and async!

**Comment by anykeyh** [comment]
I validate, I wait for finalizing the PR and I will merge it ❤️
